/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "(day start)": "（一天开始）",
    "Another day. The same you.\nMaybe it is time for a change?": "改天吧。还是那个你。也许是时候改变一下了？",
    "Attributes": "属性",
    "CHA": "魅力",
    "Charisma": "魅力",
    "Coins": "金币",
    "Close all": "全部关闭",
    "Day": "天",
    "day": "天",
    "End day": "结束一天",
    "Next >": "下一个 >",
    "Resources": "资源",
    "Required:": "要求:",
    "Status": "状态",
    "Skills": "技能",
    "SE": "社交能量",
    "Social Energy": "社交能量",
    "Town": "小镇",
    "WIS": "智慧",
    "Wisdom": "智慧",
    "Tutorial": "教程",
    "Time to pay rent.": "该付房租了。",
    "The time in the game is divided into days.": "游戏的时间以天为单位。",
    "STR": "力量",
    "Strength": "力量",
    "Continue": "继续",
    "INT": "智力",
    "Intelligence": "智力",
    "LCK": "幸运",
    "Luck": "幸运",
    "Required to pass:": "要求通过：",
    "Physical Energy": "身体能量",
    "PE": "身体能量",
    "CON": "体质",
    "Constitution": "体质",
    "Game Version Updated": "游戏版本已更新",
    "Items": "物品",
    "If there are any errors, they may be due to the current game data being incompatible with the new version.": "如果有任何错误，它们可能是由于当前游戏数据与新版本不兼容。",
    "Restarting the run will reset the data and solve those problems.": "重新启动运行将重置数据并解决这些问题。",
    "The game has been updated to version": "游戏已经更新到版本",
    "(Don't do it yet)": "（先别这么做）",
    "(New)": "(新)",
    "/s": "/秒",
    "Add your": "添加你的",
    "BUY (": "购买 (",
    "Click at the Town.": "点击小镇菜单。",
    "Food": "食物",
    "Forest": "森林",
    "Next": "下一个",
    "Type:": "类型:",
    "Tier:": "层级:",
    "max": "最大",
    "Market": "市场",
    "Library": "图书馆",
    "Mines": "矿井",
    "Maybe": "可能",
    "Smithy": "铁匠铺",
    "Return": "返回",
    "gives:": "给予:",
    "A good night's sleep will restore it.": "好好睡一觉就能恢复。",
    "Achievements can provide a bonus on your next run.": "成就可以为你的下一次运行提供奖励。",
    "Activities": "活动",
    "Activity": "活动",
    "Can you find the right buttons to press to get through the game?": "你能找到正确的按键来通关吗？",
    "Check upcoming events": "查看即将举行的活动",
    "Clicking a button will cost resources and provide a reward.": "点击按钮将消耗资源并提供奖励。",
    "Coins can be used to acquire goods and services.": "硬币可以用来购买商品和服务。",
    "currency": "货币",
    "Different town locations are relevant for different routes through the game.": "不同的城镇位置与不同的游戏路线相关。",
    "Each point of": "每一点",
    "If you are successful, you will unlock achievements.": "如果你成功了，你将解锁成就。",
    "If you fail it, the run will end.": "如果你失败了，比赛就结束了。",
    "In": "在",
    "Interacting with others depletes it.": "与他人互动会耗尽它。",
    "It also affects your damage in battle.": "它也会影响你在战斗中的伤害。",
    "No upgrades currently available": "目前没有可用的升级",
    "Now you are on your own.": "现在你得靠自己了。",
    "On some days there will be a challenge to overcome.": "在某些日子里，会有挑战需要克服。",
    "Plant a potato": "种土豆",
    "Potatoes are a great source of": "土豆是一个很好的营养来源",
    "Progress in the game is made by clicking buttons at Town locations.": "在游戏中，玩家可以点击城镇位置的按钮。",
    "Temple": "寺庙",
    "To continue, click at Your home.": "要继续，请点击您的家。",
    "Town Hall": "市政厅",
    "Starting Out": "初出茅庐",
    "Used for physical activities.": "用于体育活动。",
    "value to other attributes in various situations": "值在不同情况下赋给其他属性",
    "When you have used up all your energy for the day, click on END DAY. A new day will start with all your energy restored.": "当你用完一天的能量后，点击结束一天。新的一天将在你精力充沛的时候开始。",
    "While you will soon have thousands of other resources, social energy will remain limited, so use it wisely.": "虽然你很快就会拥有成千上万的其他资源，但社会能量仍然是有限的，所以要明智地使用它。",
    "Your home": "你的家",
    "Your Home": "你的家",
    "Carve a figurine out of a potato": "用土豆雕刻一个小雕像",
    "Carve potatoes": "雕刻土豆",
    "Calendar": "日历",
    "or": "或",
    "Just a regular day.": "只是普通的一天。",
    "Select a day to see more information about it.": "选择一天查看更多相关信息。",
    "Win a fight": "赢得一场战斗",
    "You become stronger.": "你会变得更强大。",
    "The end of the demo version": "演示版终局",
    "Credits": "鸣谢",
    "Game version:": "游戏版本:",
    "Manage game data": "管理游戏存档",
    "Close": "关闭",
    "Food is used to feed your character.": "食物是用来喂养你的角色的。",
    "Game data": "游戏数据",
    "Load data from file": "从文件导入存档",
    "material": "材料",
    "SFX Volume": "音效音量",
    "Music Volume": "音乐音量",
    "Restart Game": "重新开始游戏",
    "Save data as file": "导出存档为文件",
    "Use scientific notation": "使用科学记数法",
    "You got it": "已拥有",
    "Base": "基础",
    "Highest Item": "最多物品",
    "Chat": "聊天",
    "Engage in small talk": "进行闲聊",
    "Ardan": "阿丹",
    "Greetings! You look capable. Are you here to work in the mines?": "您好！你看起来很能干。你是来矿山工作的吗？",
    "Mine overseer": "矿井监工",
    "Mining": "采矿",
    "Neutral": "中立",
    "Relationship:": "关系:",
    "says:": "说:",
    "Social": "社交",
    "Upgrade": "升级",
    "Upgrades": "升级",
    "per second.": "每秒.",
    "Stone": "石头",
    "Requires:": "要求:",
    "to max": "到最大",
    "total)": "总计)",
    "Iron": "铁",
    "As a special first time bonus, you get some extra! Good luck!": "作为特殊的首次奖励，你可以额外获得一些！好运！",
    "Each brings 1": "每个带1",
    "Hire a Stone Miner": "雇佣一名采石工人",
    "Hire an Iron Miner": "雇佣一个铁矿工人",
    "License": "许可证",
    "License Subscription": "许可证订阅",
    "Lift some": "举起一些",
    "Lift stones": "抬石头",
    "Mining license": "采矿许可证",
    "mining Licenses": "采矿许可证",
    "Mining Licenses": "采矿许可证",
    "Negotiate better terms": "协商更好的条件",
    "Negotiate to get 1": "协商获得1",
    "out of the way.": "偏僻的。",
    "per each point of": "每一个点",
    "per negotiation": "每次协商",
    "Relationship with Ardan": "与阿丹的关系",
    "The workout will strengthen your muscles.": "锻炼会增强你的肌肉。",
    "Yes, this is one of the pickaxes the boys use. Hey, you're holding it like a natural!": "是的，这是男孩们用的镐之一。嘿，你握得很自然！",
    "A new day will start.": "新的一天将会开始。",
    "End the day.": "结束一天。",
    "Iron is cheap and versatile.": "铁便宜而且用途广泛。",
    "Restore your status.": "恢复你的状态。",
    "The most primitive of materials": "最原始的材料",
    "Yesterday felt nice.\nMaybe do even more today?": "昨天感觉很好。也许今天再多做点？",
    "Lost the game.": "输掉了游戏。",
    "Cost:": "成本:",
    "Talismans": "护身符",
    "Start with 100 extra relationship points with Ardan.": "一开始与 阿丹 的关系值额外增加100点。",
    "Start with 100 extra relationship points with Grek.": "一开始与 格雷克 的关系值额外增加100点。",
    "Start with 100 extra relationship points with Leona.": "一开始与 莉昂娜 的关系值额外增加100点。",
    "Start with 100 extra relationship points with Robert.": "一开始与 罗伯特 的关系值额外增加100点。",
    "Start with 100 extra relationship points with Runa.": "一开始与 露娜 的关系值额外增加100点。",
    "Start with 100 extra relationship points with Tiafel.": "一开始与 蒂亚菲尔 的关系值额外增加100点。",
    "Start with 100 extra relationship points with Val'Ririth.": "一开始与 瓦尔里瑞斯 的关系值额外增加100点。",
    "Gain:": "获得:",
    "Hyper Heal": "超级治愈",
    "General Killer": "普通杀手",
    "General Knowledge": "普通知识",
    "General Understanding": "一般理解",
    "Kaboom!": "大爆炸!",
    "extra": "额外的",
    "Weapons": "武器",
    "Also Felt Pain": "也感到了痛苦",
    "Anti Assassin Association": "反刺客协会",
    "Armor items": "护甲物品",
    "Attribute bonus:": "属性加成：",
    "Become close with Ardan.": "和阿丹变得亲密。",
    "Become close with Grek.": "与格雷克亲近。",
    "Become close with Leona.": "和莉昂娜走得很近。",
    "Become close with Robert.": "和罗伯特亲近起来。",
    "Become close with Runa.": "与露娜拉近关系。",
    "Become close with Tiafel.": "与蒂亚菲尔拉近关系。",
    "Become close with Val'Ririth.": "与瓦里瑞斯亲近。",
    "Become friends with Ardan.": "和阿丹成为朋友。",
    "Become friends with Grek.": "和格雷克成为朋友。",
    "Become friends with Leona.": "和莉昂娜成为朋友。",
    "Become friends with Robert.": "和罗伯特成为朋友。",
    "Become friends with Runa.": "和露娜成为朋友。",
    "Become friends with Tiafel.": "和蒂亚菲尔成为朋友。",
    "Become friends with Val'Ririth.": "和瓦尔里瑞斯成为朋友。",
    "Broke the Fifth Wall": "打破第五堵墙",
    "Carved potato": "雕刻的土豆",
    "Chatted with every NPC in a single game.": "在单局游戏中与所有NPC聊天",
    "Cloning Cleverness": "克隆技巧",
    "Close with Ardan": "与阿丹接近",
    "Close with Grek": "与格雷克接近",
    "Close with Leona": "与莉昂娜接近",
    "Close with Robert": "与罗伯特亲密接触",
    "Close with Runa": "与露娜接近",
    "Close with Tiafel": "与蒂亚菲尔接近",
    "Close with Val'Ririth": "以瓦尔里瑞斯结尾",
    "Completed the tutorial.": "完成教程",
    "Danger De-escalated": "逐步降级危险",
    "Detoxification": "解毒",
    "Dropped a Nuke": "投下一枚核弹",
    "Eat": "吃",
    "Empty skill Slot": "空技能槽",
    "Endless Endurance": "无尽的耐力",
    "Equipped Armor:": "装备盔甲：",
    "Equipped items:": "装备物品：",
    "Equipped Jewelry:": "装备首饰:",
    "Equipped Magic Tome:": "装备魔法书：",
    "Equipped Stress Toy:": "装备压力玩具：",
    "Equipped Talisman:": "装备法宝:",
    "Equipped Weapon:": "装备武器:",
    "Every Element": "每一个元素",
    "extra relationship points.": "额外的关系加分。",
    "Fighting Frenzy": "战斗狂热",
    "Financial Responsibility": "经济责任",
    "Friends with Ardan": "和阿丹做朋友",
    "Friends with Grek": "和格雷克做朋友",
    "Friends with Leona": "和莉安娜做朋友",
    "Friends with Robert": "和罗伯特做朋友",
    "Friends with Runa": "和露娜做朋友",
    "Friends with Tiafel": "和蒂亚菲尔做朋友",
    "Friends with Val'Ririth": "和瓦尔里瑞斯做朋友",
    "Gain 10 extra relationship points whenever you": "获得10点额外的关系点",
    "Have a snack and restore your physical energy.": "吃点零食，恢复体力。",
    "If used:": "如果使用:",
    "in a game you get": "在游戏中你得到",
    "Item information:": "物品信息：",
    "Jewelry": "珠宝",
    "Magic Tomes": "魔法书籍",
    "Nice to Meet You": "见到你很高兴",
    "No items of this type acquired yet": "还没有获得这种类型的物品",
    "None equipped": "无装备",
    "Only from equipped items.": "只能从已装备的物品中获得",
    "Other modifiers:": "其他修饰词：",
    "Paid rent.": "付房租。",
    "Patient Pathfinding": "病人寻路",
    "Political Police": "政治警察",
    "Put a Lid on It": "盖上盖子",
    "s cooldown)": "冷却时间)",
    "Seen Some Blood": "看到一些血",
    "Select an item to view its details": "选择物品查看详情",
    "Soul Ascension": "灵魂的提升",
    "Spirited Away": "千与千寻",
    "Split the Sands": "劈开沙滩",
    "Spread Self": "自我传播",
    "Start the game with": "开始游戏",
    "Strategy Schmategy": "战略策略",
    "Stress Toys": "压力玩具",
    "Such Slaughter": "这样的杀戮",
    "Temporary Death": "暂时死亡",
    "The first time you": "当你第一次",
    "The highest value from items you own. It does not have to be equipped.": "你所拥有的物品的最高价值。它不需要装备。",
    "Timeline Transfer": "时间线转移",
    "Unlocked when:": "解锁时:",
    "Victorious": "胜利",
    "White Blood Cells": "白细胞",
    "Passed Day 20 with AttrInt": "消耗体力度过第20天",
    "Assign skill?": "分配技能？",
    "Assign to skillbar": "分配到技能栏",
    "Cancel": "取消",
    "Click to assign a skill.": "点击以分配一个技能。",
    "Empty skill slot.": "空技能槽。",
    "Proceed": "继续",
    "You have a limited amount of skill slots that cannot be reassigned.": "你的技能槽数量有限，不能重新分配。",
    "...and that one also needs to be signed. Oh, I didn't notice you. Hello!": "．．．那张也需要签名。哦，我没注意到你。你好!",
    "...and that's how you make a sword. Would be too much for you to handle for sure!": "．．．这就是制作剑的方法。你肯定应付不了这么多！",
    "Ask for quests": "请求任务",
    "Connector": "连接器",
    "Connector resource": "连接器的资源",
    "Core": "核心",
    "Core resource": "核心资源",
    "Crafting": "制作",
    "Current quests:": "当前任务:",
    "Draw": "画",
    "Draw water": "打水",
    "from the well": "从井里",
    "Get a new list of 5 quests.": "获得5个任务的新列表。",
    "Get your home connected to the town": "让你的家和镇上联网",
    "Improved Crafting": "改进工艺",
    "Install tap": "安装水龙头",
    "Invest": "投资",
    "Just bring me the materials and I will make it.": "把材料给我，我来做。",
    "Learn how to fill out paperwork. Unlocks forgery": "学习如何填写文件。解锁伪造",
    "Learn paperwork": "学习文书工作",
    "Locked quests will not be rerolled": "锁定的任务不会被重新滚动",
    "Mayor": "市长",
    "No investments currently available.": "目前没有可用的投资。",
    "None yet. Use the button above to get started.": "还没有。使用上面的按钮开始。",
    "Normally you can craft 1 of each item. Get this upgrade to increase that limit to 2": "通常你可以制作1件物品。用这个升级把这个限制增加到2",
    "not selected": "未选中",
    "Quests": "任务",
    "Quests completed:": "任务完成:",
    "Quests requirements and rewards increase as you complete more quests.": "任务要求和奖励随着你完成更多任务而增加。",
    "Relationship with Robert": "与罗伯特的关系",
    "Relationship with Runa": "与露娜的关系",
    "resource": "资源",
    "Robert": "罗伯特。",
    "Runa": "露娜",
    "Select": "选择",
    "Select a slot to add a resource": "选择需要添加资源的槽位",
    "Smith": "史密斯",
    "Some quests only become available as you have completed a certain number of them.": "有些任务只有在你完成了一定数量的任务后才可用。",
    "supply": "供应",
    "Ugh. I guess you are here to see me.": "啊。我猜你是来找我的。",
    "Water": "水",
    "and": "和",
    "Buy": "购买",
    "Depth": "深度",
    "Drop": "掉落",
    "Grek": "格雷克",
    "Go Deeper": "更深",
    "Level": "等级",
    "Left": "左",
    "Leona": "莉昂娜",
    "Logs": "原木",
    "Next (": "下一个 (",
    "Right": "右",
    "Retry": "重试",
    "Success!": "成功!",
    "Start level": "开始关卡",
    "Wood": "木头",
    "WIS)": "智慧)",
    "Sell": "出售",
    "Selling:": "出售中:",
    "Tiafel": "蒂亚菲尔",
    "Rotate": "旋转",
    "points.": "点数.",
    "score": "分数",
    "resources:": "资源:",
    "Score:": "分数:",
    "Redo": "重做",
    "Read": "阅读",
    "Reading": "阅读",
    "Trade": "交易",
    "Trading": "交易",
    "WASD or arrow keys": "WASD 或 箭头键",
    "Vessel": "船",
    "Val'Ririth": "瓦尔里瑞斯",
    "Write": "写作",
    "Writing": "写作",
    "You died": "你挂了",
    "You have acquired:": "您已获得:",
    "...and that one also needs to be signed. Oh, I didn't notice you. Hello": "...那张也需要签名。哦，我没注意到你。你好",
    "(Maximum output:": "(最大输出:",
    "Analysis Pending": "待分析",
    "Analyze": "分析",
    "Analyzing": "分析",
    "Be sure to practice and you will eventually reach enlightenment. Praise the Great Ones!": "一定要练习，你最终会开悟的。赞美那些伟大的！",
    "Blocks left:": "左方块：",
    "but not high enough.": "但还不够高。",
    "Chop wood": "砍木头",
    "Comes from trees.": "来自树木。",
    "Complete Trade Now (": "立即完成交易(",
    "component": "组件",
    "concept": "概念",
    "Congratulations! You are amazing.": "恭喜你！你太厉害了。",
    "Controls:": "控制:",
    "equal to your score.": "等于你的分数。",
    "Final score:": "最终得分：",
    "for": "用于",
    "Forest Depths": "森林深处",
    "fragment": "碎片",
    "Hello! Nice to see another customer. How may I assist you today?": "你好!很高兴又见到一位顾客。今天我能为您做些什么？",
    "Hermit": "隐士",
    "Hire a Lumberjack": "雇佣一个伐木工人",
    "Imbue": "灌输",
    "Librarian": "图书管理员",
    "Match 4 or more of the same type.": "匹配4个或更多的相同类型。",
    "Material": "材料",
    "Merchant": "商人",
    "No tradeable resources": "没有可交易的资源",
    "Priestess": "女祭司",
    "Realize": "实现",
    "Relationship with Grek": "与希腊语的关系",
    "Required": "要求",
    "Required score:": "要求分数：",
    "Required to start the level:": "开始这个关卡需要：",
    "Spiritual": "精神",
    "Supporting": "辅助",
    "Take down a few trees.": "砍倒几棵树。",
    "To get more points, remove as many blocks with one move as possible.": "为了得到更多的分数，用一个动作移除尽可能多的方块。",
    "To win the level, you must score": "要赢得这一关，你必须得分",
    "Transaction result:": "交易结果:",
    "Transaction setup:": "事务设置:",
    "Ugh. Just when thought it alone and quiet.": "啊。只是当它独自而安静的时候。",
    "Uhhm... Hello.": "唔...你好。",
    "Use the above buttons,": "使用上面的按钮，",
    "Winning the level will permanently grant +": "获得该等级将永久获得+",
    "You have completed all the levels.": "你已经完成了所有关卡。",
    "Your analysis powers sure are formidable!": "你的分析能力一定是强大的！",
    "Your ATK:": "你的攻击：",
    "Your score was nice,": "你的分数不错，",
    "Choose": "选择",
    "gain rate": "收益率",
    "Greater Strength": "更大的力量",
    "Love for Flannel": "法兰绒之爱",
    "Proper nutrition": "适当的营养",
    "Tasty Recipes": "美味的食谱",
    "What you learned is:": "你学到的是：",
    "You have learned something from your daily activities.": "你从日常活动中学到了一些东西。",
    "Equip": "装备",
    "Equipped": "已装备",
    "Ideas": "主意",
    "A potato carved into a shape that brings luck.": "被雕刻成能带来好运的形状的土豆。",
    "Bad Idea": "坏主意",
    "Book recommendations": "书籍推荐",
    "Click to view details": "点击查看详情",
    "for books to read": "供阅读的书",
    "Get 1": "获得1个",
    "Hire a tutor to teach you how to think faster.": "雇一个家教来教你如何更快地思考。",
    "I can recommend you a book or two if": "如果可以的话，我可以给你推荐一两本书",
    "ideas whenever you read books": "每当你读书的时候",
    "Improve library catalogue": "改进图书馆目录",
    "Lesson from a tutor": "导师的教训",
    "Make finding books in the library easier.": "让在图书馆找书更容易。",
    "Mental Energy": "精神能量",
    "ME": "精神能量",
    "Mining License": "采矿许可证",
    "Okay, this part of the mines is now temporarily allocated to you. Good luck!": "好吧，这部分矿场现在暂时分配给你。好运！",
    "Read a book": "读一本书",
    "Recomm": "推荐",
    "Recommendation": "推荐",
    "Relationship with Tiafel": "与蒂亚菲尔的关系",
    "This book had some very interesting ideas.": "这本书有一些非常有趣的观点。",
    "Bones": "骨头",
    "(ATK:": "(攻击:",
    "eaten at once": "一次性吃",
    "from": "从",
    "HP": "生命值",
    "Hire a Hunter": "雇佣一个猎人",
    "Health Points": "生命值点数",
    "Giant Rat": "巨鼠",
    "Make": "制作",
    "Leather": "皮革",
    "restored": "恢复",
    "Upgrades:": "升级:",
    "to restore": "去恢复",
    "Redo Level": "重做等级",
    "Make paper": "造纸",
    "for it.": "对于它。",
    "Add protein": "添加蛋白质",
    "Add texture": "添加纹理",
    "Angry Plant": "愤怒的植物",
    "Food is nicer if you add it some texture.": "如果你给食物添加一些质感，它会变得更好吃。",
    "Gotta pay rent tomorrow morning.\nLast chance to scrape up": "明天早上要交房租了。最后一次凑钱的机会",
    "Healing Service": "治疗服务",
    "If you think a lot, it will run out.": "如果你想得太多，它就会耗尽。",
    "Must go too if you go to forest. That my task.": "如果你要去森林，你也必须去。那是我的任务。",
    "My spell will mend the cracks in your soul's vessel.": "我的咒语会修补你灵魂之容器的裂缝。",
    "Some extra protein makes your muscles stronger.": "一些额外的蛋白质会让你的肌肉更强壮。",
    "The Angry Plant has died.": "愤怒的植物已死亡",
    "The Giant Rat has died.": "巨鼠已死亡",
    "Wash it down": "把它吞下去",
    "You can eat more if you make it slippery.": "如果你把它弄得很滑，你可以吃得更多。",
    "You encounter a Giant Rat!": "你遇到一只巨大的老鼠！",
    "You encounter an Angry Plant!": "你遇到了一个愤怒的植物！",
    "You have been defeated.": "你被打败了。",
    "Luck is Skill": "运气是技巧",
    "Yes please": "是的, 请",
    "Gain an extra skill slot": "获得一个额外的技能槽",
    "No recipe found": "未发现配方",
    "Owned:": "拥有:",
    "Your action:": "你的动作:",
    "Your landlord appears.\nHe is demanding his money.": "你的房东出现了。他在索要他的钱。",
    "Don't pay": "不付钱",
    "Game Over": "游戏结束",
    "rent.\nYou are evicted.": "房租。你被驱逐了。",
    "Robbers in your house": "你家里有强盗",
    "Start a new game": "开始新游戏",
    "Unlocked:": "已解锁:",
    "You are not able to pay your": "你没有能力支付你的",
    "Choose up to": "最多选择",
    "Applied achievements:": "应用成就：",
    "New game": "新游戏",
    "None. Select below": "没有。选择下面",
    "Start the game": "开始游戏",
    "to apply for this game:": "以应用到本次游戏:",
    "Buy a magical device that automatically makes": "购买一个可以自动制作的神奇装置",
    "Paper": "纸",
    "Buy a paper maker": "买一家造纸厂",
    "Converts": "转换",
    "The outer layer of a soft and hairy monster.": "柔软多毛的怪物的外皮。",
    "The remains of a creature.": "一个生物的遗体。",
    "to": "到",
    "Each investment will double the lumberjacks' productivity.": "每一笔投资都会使伐木工人的生产率翻一番。",
    "funds": "资金",
    "Funds": "资金",
    "Having a lot of them makes you able to fight more.": "有很多这样的东西会让你更有能力去战斗。",
    "in various projects.": "在不同的项目中。",
    "Invest in Lumberjacks": "投资伐木工人",
    "Okay, you leave. Eatie time toad and mushroom soup.": "好吧，你走吧。早餐时间蟾蜍蘑菇汤。",
    "production (Total: x": "生产(总计：x",
    "Unlock investments": "解锁投资",
    "Unlock the ability to invest": "解锁投资能力",
    "Bright Thoughts": "聪明的想法",
    "Hugging wood": "拥抱木头",
    "Rocking and Rolling": "摇摆不定",
    "A blank canvas.": "一张空白的画布。",
    "A good idea.": "一个好主意。",
    "mental": "精神",
    "Good Idea": "好主意",
    "Max": "最大",
    "Kind Idea": "不错的主意",
    "Craft": "制作",
    "Current recipe:": "当前配方:",
    "Good book": "好书",
    "additional bricks on each level of analysis (currently": "每个分析级别上的附加模块（当前）",
    "Core concept": "核心概念",
    "Deep analysis": "深入分析",
    "Here you go, this one is a classic.": "给你，这个很经典。",
    "Improve Analysis": "改善分析",
    "Learn techniques for deeper analysis.": "学习进行更深入分析的技术。",
    "Read a good book": "读一本好书",
    "Read a kind book": "读一本不错的书",
    "Supporting concept": "支持概念",
    "Last ones": "最后一个",
    "Level Completed": "关卡完成",
    "No more bricks": "没有更多的砖块了",
    "Book": "书",
    "potato": "土豆",
    "per": "每个",
    "ideas whenever you read books (currently x": "想法当你读书 (当前 x",
    "Fertilizing your potatoes will make them grow faster": "给土豆施肥会使它们长得更快",
    "Fertilize potatoes": "施肥土豆",
    "Donate good books to the library": "捐赠好书到图书馆",
    "Donate good books": "捐赠好书",
    "Great Idea": "伟大的想法",
    "I am sorry, we don't have many books about \"getting rich fast\".": "很抱歉，我们没有很多关于“快速致富”的书。",
    "Indeed, that tome challenges the reader to grapple with the profound ambiguities inherent in the human condition.": "的确，这本书向读者提出了挑战，要他们去应对人类生存状况中固有的深刻的模糊性。",
    "Read a great book": "读一本伟大的书",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "/": "/",
    "???": "???",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Unlocked new achievement: ": "解锁新成就: ",
    "Consume": "消耗",
    "You gain loot: ": "你获得了战利品: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^\/([\d\.]+)$/,
    /^\(([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Get yourself healed for (.+) HP$/, '治愈你自己 $1 生命值'],
    [/^You hit for (.+) damage.$/, '你攻击并造成了 $1 伤害。'],
    [/^You get hit for (.+) damage.$/, '你被攻击并受到了 $1 伤害。'],
    [/^You are in Forest Depth (.+) \(Level (.+)\)$/, '你在森林深处 $1 (等级 $2)'],
    [/^Forest Depth (.+) \(Level (.+)\)$/, '森林深处 $1 (等级 $2)'],
    [/^You unlocked Forest Depth (.+) \((.+)\) and gained (.+) STR$/, '你解锁了 森林深处 $1 ($2) 并获得了 $3 力量'],
    [/^Forest Depths (.+) \(Level (.+)\)$/, '森林深处 $1 (等级 $2)'],
    [/^Forest Depths \(Level (.+)\)$/, '森林深处 (等级 $1)'],
    [/^You arrive to Forest Depth (.+) \(Level (.+)\)$/, '你到达了森林深处 $1 (等级 $2)'],
    [/^Passed Day (.+) through$/, '度过第 $1 天通过'],
    [/^Passed Day (.+) through battle$/, '度过第 $1 天通过战斗'],
    [/^Passed Day (.+) with$/, '度过第 $1 天通过'],
    [/^Start the game with (.+) additional$/, '开始游戏时有 $1 额外的'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) wood,  ([\d\.,]+) coins$/, '$1 木头，$2 金币'],
    [/^([\d\.,]+) leather,  ([\d\.,]+) coins$/, '$1 皮革，$2 金币'],
    [/^([\d\.,]+) leather,  ([\d\.,]+) bones,  ([\d\.,]+) coins$/, '$1 皮革，$2 骨头，$3 金币'],
    [/^([\d\.,]+)x more$/, '$1x 更多'],
    [/^Read and learn ([\d\.,]+) new things$/, '阅读和学习 $1 新事物'],
    [/^Read and learn ([\d\.,]+) new things with an increased chance to find good ideas$/, '阅读和学习 $1 新事物，可以增加发现好想法的机会'],
    [/^Read and learn ([\d\.,]+) new things with an increased chance to find kind ideas$/, '阅读和学习 $1 新事物，可以增加发现不错的想法的机会'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);